---
    environment: production
    chdir: /var/www/horacephair/potato
    address: 127.0.0.1
    user: root
    group: root
    port: 4567
    pid: /tmp/potato.thin.pid
    rackup: /var/www/horacephair/potato/config.ru
    log: /tmp/potato.thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: false
